# Site settings
title: Shiny Things
email: jim@jimmenard.com
description: > # this means to ignore newlines until "baseurl:"
  Jim likes shiny things. Technology is shiny.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimmenard.com" # the base hostname & protocol for your site
twitter_username: jmenard42
github_username:  jimm

# Build settings
markdown: kramdown
